version: '3.8'
services:
  dialogflow-tg-bot:
    image: delgus/dialogflow-tg-bot
    environment:
      - CREDENTIALS_JSON=${CREDENTIALS_JSON}
      - PROJECT_ID=${PROJECT_ID}
      - TG_ACCESS_TOKEN=${TG_ACCESS_TOKEN}
      - TG_WEBHOOK=${TG_WEBHOOK}
      - LOG_TG_CHAT_ID=${LOG_TG_CHAT_ID}
      - LOG_TG_ACCESS_TOKEN=${LOG_TG_ACCESS_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL}
    ports:
      - ${DEPLOY_PORT}:80
    #deploy:
      #replicas: 1
      #update_config:
        #parallelism: 2
        #delay: 3s
        #order: start-first
        #failure_action: rollback
        #monitor: 1m
     # restart_policy:
     #   max_attempts: 3
