name: deploy
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
        
    - uses: actions/checkout@v2
      
    - uses: golangci/golangci-lint-action@v1
      with:
          version: v1.27

#    - uses: docker/build-push-action@v1
#      with:
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}
#        repository: delgus/jokebot
#        tags: latest
#
#    - uses: appleboy/ssh-action@v0.0.9
#      with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USER }}
#        password: ${{ secrets.PSW }}
#        script: |
#          docker pull delgus/dialogflow-tg-bot
#          docker rm --force dialogflow-tg-bot
#          docker run --name=dialogflow-tg-bot -d -e CREDENTIALS_JSON=${{ secrets.CREDENTIALS_JSON }} -e PROJECT_ID=${{ secrets.PROJECT_ID }} -e PORT=${{ secrets.PORT }} -e TG_ACCESS_TOKEN=${{ secrets.TG_ACCESS_TOKEN }} -e TG_WEBHOOK=${{ secrets.TG_WEBHOOK}} -p ${{ secrets.DEPLOY_PORT }}:80 delgus/dialogflow-tg-bot
          
