name: deploy
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: 1.14
        
    - uses: actions/checkout@v2
      
    - uses: golangci/golangci-lint-action@v1
      with:
          version: v1.27

    - name: build
      run: CGO_ENABLED=0 make build

    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: delgus/dialogflow-tg-bot
        tags: latest

    - name: deploy
      env:
        CREDENTIALS_JSON: ${{ secrets.CREDENTIALS_JSON }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PORT: ${{ secrets.PORT }}
        TG_ACCESS_TOKEN: ${{ secrets.TG_ACCESS_TOKEN }}
        TG_WEBHOOK: ${{ secrets.TG_WEBHOOK}}
        LOG_TG_CHAT_ID: ${{ secrets.LOG_TG_CHAT_ID}} 
        LOG_TG_ACCESS_TOKEN: ${{ secrets.LOG_TG_ACCESS_TOKEN }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        DOCKER_HOST: tcp://${{ secrets.HOST }}:2376
        DEPLOY_PORT: ${{ secrets.DEPLOY_PORT }}  
      run: docker stack deploy -c deploy.yml dialogflow-tg-bot
          
